version: "3.7"

networks:
    front:
        external:
            name: gateway
    local:

services:
    apache:
        build: .docker/apache
        container_name: apache-${APP_PROJECT}
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - .docker/config/apache-vhosts.conf:/etc/apache2/vhosts.conf:ro
            - .:/home/wwwroot/sf4
        depends_on:
            - php
        networks:
            - front
            - local
        labels:
            - traefik.http.routers.apache-${APP_PROJECT}.rule=Host(`${APP_PROJECT}.sf4.local`)

    mysql:
        image: mysql
        container_name: mysql-${APP_PROJECT}
        volumes:
            - .docker/data/db:/var/lib/mysql
        networks:
            - local
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4
        labels:
            - traefik.enable=false

    php:
        build: .docker/php
        container_name: php-${APP_PROJECT}
        volumes:
            - .:/home/wwwroot/sf4
        environment:
            - maildev_host=maildev-${APP_PROJECT}
        depends_on:
            - maildev
            - mysql
        networks:
            - local
        labels:
            - traefik.enable=false

    maildev:
        image: djfarrelly/maildev
        container_name: maildev-${APP_PROJECT}
        networks:
            - front
            - local
        labels:
            - traefik.http.routers.maildev-${APP_PROJECT}.rule=Host(`maildev-${APP_PROJECT}.sf4.local`)
